package spring.tutorial.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-20T20:11:01.470+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://webservice.tutorial.spring/", name = "IBankAccountService")
@XmlSeeAlso({ObjectFactory.class})
public interface IBankAccountService {

    @RequestWrapper(localName = "addUserDetails", targetNamespace = "http://webservice.tutorial.spring/", className = "spring.tutorial.webservice.AddUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "addUserDetailsResponse", targetNamespace = "http://webservice.tutorial.spring/", className = "spring.tutorial.webservice.AddUserDetailsResponse")
    public void addUserDetails(
        @WebParam(name = "usrDetail", targetNamespace = "")
        spring.tutorial.webservice.UserDetails usrDetail
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://webservice.tutorial.spring/", className = "spring.tutorial.webservice.GetUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://webservice.tutorial.spring/", className = "spring.tutorial.webservice.GetUserDetailsResponse")
    public spring.tutorial.webservice.UserDetails getUserDetails(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName
    );
}
